In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
#Consider the below code to answer further questions:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)


In [ ]:
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [ ]:
Yes, there is a difference in the data types of variables list_ and array_list. The variable list_ is a Python list, 
while array_list is a NumPy array.

In [3]:
type(list_)

list

In [4]:
type(array_list)

numpy.ndarray

In [ ]:
Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [5]:
for element in list_:
    print(type(element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [8]:
for element in array_list:
    print(element.dtype)

<U1
<U1
<U1
<U1
<U1


In [ ]:
Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [ ]:
Yes, there will be a difference in the data type of the elements present in both variables list_ and array_list

In [11]:
array_list = np.array(object = list_, dtype = int)

In [ ]:
In this code, the dtype=int argument specifies that the elements in array_list should be converted to integers.

In [12]:
for element in list_:
    print(type(element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [13]:
for element in array_list:
    print(element.dtype)

int64
int64
int64
int64
int64


In [14]:
#Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)


In [ ]:
Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [15]:
num_array.size

6

In [16]:
num_array.shape

(2, 3)

In [ ]:
Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [19]:
arr3=np.zeros((3,3))
print(arr3.size)
print(arr3.shape)
print(arr3)

9
(3, 3)
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [21]:
arr4=np.eye(5,5)

In [22]:
arr4

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])